### PR TITLE
bug(codeeditor): Fix too many scrollbars

### LINKED ISSUE #131: Too many scrollbars
Here is an animation of the issue.
ezgif-4-4866a3b1918b

Solution: We want only the code editor vertical scrollbar.

### PR DESCRIPTION
**Pull request by sumitparakh**
Done

Fixes #131

### CODE REVIEW

**Comment by manekinekko** [comment]
Hi, that's a very good start. But I noticed there are still some inconsistencies related to the sidebars. Do you think you can improve that as well?

image

**Comment by sumitparakh** [comment]
You mean those unnecessary vertical space? Yes, I can try to fix those.

**Comment by manekinekko** [comment]
Yeah, as you can see, the horizontal scroll bar is not at the bottom but ~20px above the edge. And for the vertical scrollbar on the right, you may wanna try and disable that behavior in [this config](https://github.com/xlayers/xlayers/blob/develop/src/app/editor/code-editor/code-editor.module.ts#L28).

**Comment by sumitparakh** [comment]
Hi @manekinekko . Is there anything else I should update in this MR?

**Comment by manekinekko** [comment]
@sumitparakh sorry for the delay. I was still on holidays. The PR is ready to be merged. Thanks again for your work 👍

**Pull request merged**
