### PR TITLE
Fix error handling

### PR DESCRIPTION
**Pull request by manekinekko**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by Jefiozie** [comment]
@manekinekko I think this should resolve the issue we've had. Could you verify if this is the result you expected?

**Comment by manekinekko** [comment]
Thanks @Jefiozie. Will check this asap.

**Comment by manekinekko** [comment]
Hey @Jefiozie  I think you have accidentally merged changes from main which should not be part of this PR.

**Comment by Jefiozie** [comment]
@manekinekko  I rebased the main changes on to this branch.

**Pull request merged**
