### PR TITLE
ci: change make file to script

### PR DESCRIPTION
**Pull request by Jefiozie**
I changed the make file to a custom build script. This way we can easier support `Windows`, `Unix` and `OSX`.  It can be enhanced with other projects to come. Let me know if we would like to use this setup or I need to make some changes.

### CODE REVIEW

**Comment by Jefiozie** [comment]
@manekinekko could you verify if the changes I made a correct?

**Comment by manekinekko** [comment]
@Jefiozie I'd really love it if we can have de log messages while building (in case of issues). Do you think this is possible? Also, the ora output doesn't seem to work well with Netlify. Do you have access to the Nelify logs?

**Comment by Jefiozie** [comment]
The error's where caused by a reference problem in the NPM script. 
Going to check if we can do more with the output of logging.

**Comment by Jefiozie** [comment]
logging is included 👍

**Comment by Jefiozie** [comment]
After #330 is merged I will update this PR with the new library's.

**Pull request merged**
