### PR TITLE
feat(ui): make home page responsive

### PR DESCRIPTION
**Pull request by sumitparakh**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
Currently the home page is not mobile friendly . 

Issue Number: #315 

## What is the new behavior?
It is responsive now.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by sumitparakh** [comment]
@Jefiozie  can you check now?

**Comment by Jefiozie** [comment]
It looks much better, but maybe we should remove the zooming, what do you think @manekinekko ?

**Comment by manekinekko** [comment]
@sumitparakh we have discussed this and decided that we will remove the zoom bloc when we are on mobile. Would you mind updating your PR accordingly?

**Comment by sumitparakh** [comment]
> @sumitparakh we have discussed this and decided that we will remove the zoom bloc when we are on mobile. Would you mind updating your PR accordingly?

Sure.

**Comment by sumitparakh** [comment]
@manekinekko . It's done

**Pull request merged**
