### PR TITLE
WIP Feature/include stenciljs

### PR DESCRIPTION
**Pull request by romulocintra**
WIP for #137

### CODE REVIEW

**Comment by romulocintra** [comment]
Just rebased old commit messages , at this moment don't see a valuable integration with stencil : 

1. Cannot use it with stackblitz
2. When i download only have base files to include in a stenciljs project and all works well

At this moment don't see as added value integrate this. but opens a good opportunity to include LitElement or something that we can run with the same value than the others...

**Comment by romulocintra** [comment]
> We are thinking about making stackblitz integration configurable. So we can enable/disable it on demand. thanks a lot for this PR. We will keep it as a ref for the moment. And I will merge when needed.

Yes, i was thinking the same, also something like feature toggles, or a badge (beta / alpha / new) for most recent integrations that aren't stable.

At moment don't have much time but I will try to investigate how to run the demo, probably in glitch we can run.

**Comment by manekinekko** [comment]
Hey @romulocintra we are about to merge your changes, could you please rebase this PR on dev?

**Comment by romulocintra** [comment]
Hi @manekinekko  i will

**Comment by romulocintra** [comment]
@manekinekko  rebased and modified code to be compliant with new versions

**Pull request merged**
