### PR TITLE
ci: stamp version without rebuilding

### PR DESCRIPTION
**Pull request by Jefiozie**
This PR will stamp our JS files without rebuilding the xlayers app.

### CODE REVIEW

**Comment by manekinekko** [comment]
@Jefiozie the stamping does not seem to be working.

image

**Comment by Jefiozie** [comment]
Is this local with `ng serve`? If that is the case then it could be possible. At this moment we only support production bundles that are hosted via a webserver. If we would like to support the command  `ng serve` we should make some changes.

**Comment by manekinekko** [comment]
Actually I checked this on the Netlify preview URL: https://deploy-preview-390--xlayers.netlify.app/

**Comment by Jefiozie** [comment]
What scripts do we run for netlify? Could you show/ tell me

**Comment by manekinekko** [comment]
I think it's `npm run build`. So you can run the stamp process in a `postbuild` script

**Comment by Jefiozie** [comment]
With the latest adjustments this should be fixed:
image

**Comment by Jefiozie** [comment]
@manekinekko, I think this one is done now and ready for review and merge.

**Pull request merged**
