### PR TITLE
fix(translations): translate pointer on landing pages

### PR DESCRIPTION
**Pull request by sumitparakh**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
Landing page screenshots are not translated as per browser landing. Please refer to the screenshot in the issue below

Issue Number: #311 

## What is the new behavior?
Translation added.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by sumitparakh** [comment]
@Jefiozie  I've used google translate so let me know if translations are correct or not

**Comment by Jefiozie** [comment]
Thank you @sumitparakh, I will have a look at your PR in upcoming days and get back to you. 😃

**Comment by sumitparakh** [comment]
@Jefiozie  all done.

**Comment by Jefiozie** [comment]
LGTM

**Pull request merged**
