### PR TITLE
Embed StackBlitz

### PR DESCRIPTION
**Pull request by Jefiozie**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #240 

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by Jefiozie** [comment]
I have tried to implement a "loader" for the `iframe` of stackblitz but for some reason I got really bad UI artifacts. So I dropped this idea and used the `clickToLoad` functionality off stackblitz for now. 
All things are looking pretty good for now as far as I can see.

I'm sending this PR in for a first round off feedback and to get some input from other people on how you think the behavior is.  After some feedback I will have a look at some basic tests around it to get some code quality and I will do some small refactoring around the code. 

Things I think I should finish before putting this in master:

- [ ] unit tests
- [ ] e2e tests
- [ ] better reactive approach on the `VM` handeling
- [ ] reference `xlayer` file for the stackblitz editor so that people are straight in the generate code.

Not related to this specifc topic I have created a bug at Stackblitz as I looks like the have not disabled the `Redux DevTools` on the enviroment. [stackblitz/core #904](https://github.com/stackblitz/core/issues/904)

**Comment by Shikanime** [comment]
Looks like the footer of the iframe is hidden.

image

**Comment by Jefiozie** [comment]
thanks for the feedback!

**Comment by manekinekko** [comment]
Hi @Jefiozie after discussing this with @Shikanime we think that the user experience when embedding stackblitz is unstable. I think we should revert to the previous configuration and just have a code block with syntax highlighting, and giving the choice to the users to open stackblitz outside of xlayers.dev if they will.

However, we'd like to keep the top bar with the frameworks list. What do you think?

image

**Comment by Jefiozie** [comment]
Hi @Shikanime & @manekinekko,

I think you are right about stackblitz and the framework list. The is a nice feature that we should contain as it will gain user experience for selecting a different framework. 

Probably we need a loader when switching between one of these right?


Thanks for the feedback!

**Comment by Jefiozie** [comment]
Closing this in favor off a new PR coming next week.

**Pull request closed without merging**
