### PR TITLE
fix(test): e2e test is failing in main branch

### LINKED ISSUE #429: e2e test is failing in main branch
**Describe the bug**

Whenever any PR is merged to main, github action runs some tests in which e2e test case is failing.

**To Reproduce**
1. Merge any PR to main
2. Check github action like this:-
https://github.com/xlayers/xlayers/runs/2935222271

**Expected behavior**
Tests should pass

**Screenshots**
image

### PR DESCRIPTION
**Pull request by sumitparakh**
Closes #429

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #429 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by Jefiozie — CHANGES_REQUESTED** [review]
Hi @sumitparakh, could you have a look why the test is failing? Thanks

**Comment by sumitparakh** [comment]
Sure

**Comment by sumitparakh** [comment]
@Jefiozie . It is fixed.

**Review by Jefiozie — APPROVED** [review]
LGTM

**Pull request merged**
