### PR TITLE
chore: add Bazel support

### PR DESCRIPTION
**Pull request by manekinekko**

### CODE REVIEW

**Comment by manekinekko** [comment]
Blocked by: https://github.com/bazelbuild/bazel/issues/6176

**Comment by manekinekko** [comment]
See https://github.com/alexeagle/angular-bazel-example/pull/228

**Comment by Shikanime** [comment]
How far is your implementation ? There is no issue open for this pr.

**Comment by manekinekko** [comment]
The feature issue was simply: switch the build system to bazel :D

**Pull request closed without merging**
