### PR TITLE
feat(changelog) added changelog

### PR DESCRIPTION
**Pull request by Jefiozie**
First setup to start discussion around this. In the issue I have added a couple of questions.

Closes: #172

### CODE REVIEW

**Comment by manekinekko** [comment]
Hey, great! thanks.

Do you know why some of the changes are duplicated: https://github.com/xlayers/xlayers/blob/bbd9af93c0573e5a217f6d64ba3e5525fe968997/CHANGELOG.md

**Comment by Jefiozie** [comment]
I have had a look but I don't. I can see from the git history that there are really multiple commits with the same description. I also looked at other projects using this package and all are doing the same.

Do you merge or squash commits? Maybe it is related with this?

**Comment by Jefiozie** [comment]
Maybe a cool idea to add `Xlayers` to the Release Butler (when we have a correct Changelog)  [release butler](https://twitter.com/releasebutler)

**Comment by manekinekko** [comment]
Yep, I'll ping Thomas for that. Thanks for the suggestion :)

**Comment by manekinekko** [comment]
We usually squash and merge.

**Comment by Jefiozie** [comment]
> Do you know why some of the changes are duplicated: [/CHANGELOG.md@`bbd9af9`](https://github.com/xlayers/xlayers/blob/bbd9af93c0573e5a217f6d64ba3e5525fe968997/CHANGELOG.md)


So I investigated this problem and it looks "correct". It looks like this behaviour:

>"duplicate commits" behavior is usually to do a rebase of a branch that has been already pushed to a remote repository and then merge it back to that same remote branch. The rebase will change the IDs of your commits and the merge will keep both pairs of "duplicate" commits, even though their changes will result in the same content.

See pic 1 branch "a":
pic1

See pic 1 branch "b":
pic2


To resolve this we need to rewrite history in git. Maybe this is a bit to much?

**Comment by manekinekko** [comment]
You are awesome! thanks for investigating this. If this is too much. We can deprioritize this feature. It's not really urgent to have it right now. WDYT?

**Comment by Jefiozie** [comment]
I'm willing to have a look. I believe we have a couple of options.

1. Rewrite Git history.
2. Accept it as is and have a good commit strategy (using commit lint rules)
3. A other idea?

**Comment by Jefiozie** [comment]
Maybe @Shikanime has a other idea around this topic?

**Comment by manekinekko** [comment]
rewriting the git history sounds radical. but why not if we have the guarantee that it will fix the changelog output. let's think about it in more details. @Shikanime wdyt?

**Comment by Jefiozie** [comment]
Or we can just rewrite history for the duplicates? 😎

**Pull request merged**
