### PR TITLE
feature(editor): Download image preview

### PR DESCRIPTION
**Pull request by Jefiozie**
Added a default download icon to the preview. 
Closes: #129

### CODE REVIEW

**Comment by Shikanime** [comment]
Hi Jefiozie !
All good, I was also thinking that it might look super cool something like this 😀
image

**Comment by Jefiozie** [comment]
I like that idea 😃 let me have a look at it!

**Comment by Shikanime** [comment]
We can hardly see the icon with the white~gray background color. Maybe a `#1e1e1e` and everything should be perfect 👌

**Comment by Jefiozie** [comment]
Changed the color 👍 Do you want me to squash the commits?

**Comment by Jefiozie** [comment]
> Changed the color 👍 Do you want me to squash the commits?

Already squashed it as I think this is nicer.

**Pull request merged**
