### PR TITLE
fix: change stackblitz services so that it will work with new generators

### PR DESCRIPTION
**Pull request by Jefiozie**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature (please, look at the "Scope of the project" section in the README.md file)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by Jefiozie** [comment]
This will resolve our problems with the stackblitz exports. However, I don't really like the way I quickly fixed it now. Let us discuss the way we would like this to be for a future proof setup.


Some questions think we should discuss: 

- Do we want to use the inline templating as it is now?
- Is the page1 component always the root component?
- Should the framework specific service be an angular service our do we want this to be a `Typescript` class?

**Comment by Jefiozie** [comment]
Will be blocked by #339 as we introducing a new concept `bootstrap service`. After merging in #339 I will look into this PR again.

**Comment by manekinekko** [comment]
When previewing the PR, it seems that the codegen is broken, for Angular at least.

image

image

**Comment by Jefiozie** [comment]
@manekinekko, thanks for looking into the PR. 

I looked at your reporter issues, I already fixed the routing problem this was just a typo 🎉

However, the other one is a bit harder, I see that when you select the  `md-component-status-bar` you will have the issue as is visible in your screenshots. If I use another demo file I cannot reproduce the issue. I believe it has something to do with the codegen part and is not related to the Stackblitz adjustments (still I need to dig a bit deeper to know this for sure).

I will update this PR if I have some more findings.

**Comment by Jefiozie** [comment]
@manekinekko @Shikanime I'm going to merge this as the issue is not related to these fixes.

**Pull request merged**
